util: use if condition to check for secrets

diff --git a/.github/workflows/secrets.yml b/.github/workflows/secrets.yml
--- a/.github/workflows/secrets.yml
+++ b/.github/workflows/secrets.yml
@@ -1,20 +1,30 @@
-name: Try to get secrets
+name: Check for secrets
 
 on:
   workflow_call:
-
-env:
-  DATABASE_URI: ${{ secrets.DATABASE_URI }}
-  PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
 
 jobs:
   test-secrets:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      - run: |
-          echo "This is the ${{ secrets.DATABASE_URI }} environment variable"
-          echo "This is the ${{ secrets.PAYLOAD_SECRET }} environment variable"
-          echo "This is the ${{ secrets.VERCEL_TOKEN }} environment variable"
-          echo "This is the ${{ secrets.ORG_ID }} environment variable"
-          echo "This is the ${{ secrets.PROJECT_ID }} environment variable"
+      - if: "${{ secrets.DATABASE_URI != '' }}"
+        run: |
+          echo "Missing DATABASE_URI secret"
+          exit 1
+      - if: "${{ secrets.PAYLOAD_SECRET != '' }}"
+        run: |
+          echo "Missing PAYLOAD_SECRET secret"
+          exit 1
+      - if: "${{ secrets.VERCEL_TOKEN  != '' }}"
+        run: |
+          echo "Missing VERCEL_TOKEN secret"
+          exit 1
+      - if: "${{ secrets.ORG_ID != '' }}"
+        run: |
+          echo "Missing ORG_ID secret"
+          exit 1
+      - if: "${{ secrets.PROJECT_ID != '' }}"
+        run: |
+          echo "Missing PROJECT_ID secret"
+          exit 1
